// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByqm0UkZuMZSWAm6grfIwvgusyVJ6fMY0',
    appId: '1:927142922437:web:9f2e57e12159360e9188ac',
    messagingSenderId: '927142922437',
    projectId: 'virclinic-fcf3e',
    authDomain: 'virclinic-fcf3e.firebaseapp.com',
    storageBucket: 'virclinic-fcf3e.firebasestorage.app',
    measurementId: 'G-8TGK0SKQKN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsZS_TsGvqnFfRb310I6UquhEqwdFl11E',
    appId: '1:927142922437:android:10a4023669fab6189188ac',
    messagingSenderId: '927142922437',
    projectId: 'virclinic-fcf3e',
    storageBucket: 'virclinic-fcf3e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAajNBJ_FV2ptPZDeMe8C3XD0OSfu4a-xQ',
    appId: '1:927142922437:ios:99056340f63363379188ac',
    messagingSenderId: '927142922437',
    projectId: 'virclinic-fcf3e',
    storageBucket: 'virclinic-fcf3e.firebasestorage.app',
    iosBundleId: 'com.example.patienApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAajNBJ_FV2ptPZDeMe8C3XD0OSfu4a-xQ',
    appId: '1:927142922437:ios:99056340f63363379188ac',
    messagingSenderId: '927142922437',
    projectId: 'virclinic-fcf3e',
    storageBucket: 'virclinic-fcf3e.firebasestorage.app',
    iosBundleId: 'com.example.patienApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByqm0UkZuMZSWAm6grfIwvgusyVJ6fMY0',
    appId: '1:927142922437:web:e9d98306ddf5c93c9188ac',
    messagingSenderId: '927142922437',
    projectId: 'virclinic-fcf3e',
    authDomain: 'virclinic-fcf3e.firebaseapp.com',
    storageBucket: 'virclinic-fcf3e.firebasestorage.app',
    measurementId: 'G-RSRMZBD9J8',
  );
}
